name: Build and Release Python Exe

on:
  workflow_dispatch:
  create:
    branches:
      - "release/V.*"

jobs:
  build-and-release:
    if: startsWith(github.ref, 'refs/heads/release/V.*')
    runs-on: windows-latest 

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install PyInstaller
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Build the Exe with PyInstaller
      - name: Build Exe
        run: |
          pyinstaller --onefile src/main.py --name AIChatBot
          ls dist/  # Überprüfen, ob die Datei erstellt wurde

      # Create a GitHub Release and Upload the Exe
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/AIChatBot.Exe
          token: ${{ secrets.Token}}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release contains the compiled Python Executable.
            - **File:** `AIChatBot.exe`
          replacesArtifacts: true 
