name: Build and Release EXE

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile src/main.py --name main_executable
          ls dist/

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: main_executable
          path: dist/main_executable.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download EXE Artifact
        uses: actions/download-artifact@v3
        with:
          name: main_executable

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: main_executable.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release contains the compiled executable for branch ${{ github.ref_name }}.