name: Python Quality Assurance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit safety vulture radon pydocstyle black isort mypy

      - name: Syntax and Style Check with flake8
        run: flake8 .

      - name: Security Check with Bandit
        run: bandit -r .

      - name: Dependency Security Check
        run: safety check -r requirements.txt

      - name: Dead Code Detection with Vulture
        run: vulture .

      - name: Code Complexity Check with Radon
        run: radon cc . -a

      - name: Documentation Check with pydocstyle
        run: pydocstyle .

      - name: Code Formatting Check with Black
        run: black --check .

      - name: Import Sorting Check with isort
        run: isort --check-only .

      - name: Type Checking with MyPy
        run: mypy .
