name: Python Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Tests
      - name: Run Tests
        uses: ./.github/actions/run-tests

      # Build the Project
      - name: Build Project
        uses: ./.github/actions/build
